### PR TITLE
Normalized Unicode strings before converting them to an array

### PR DESCRIPTION
**Pull request by sebastien-fauvel**
- Fixes PDF rendering issues with combining diacritical marks
- Depends on PECL intl >= 1.0.0 (optional)

### CODE REVIEW

**Comment by nicolaasuni** [comment]
As you can see, the proposed change breaks the existing tests.
Please note that the strToChrArr is already complete as atomic function.
If you need to normalize a string, you should introduce another method and write the specific test for it.
Note that normalization may be unwanted in some cases.
Maybe the normalization should be handled by the library (the new TCPDF) that is calling this one.
The old TCPDF library issues cannot be directly ported here as there are significant architectural changes.

**Comment by sebastien-fauvel** [comment]
I agree in principle – this should be text preprocessing. Please move it to the new TCPDF library as soon as possible!

**Comment by sebastien-fauvel** [comment]
But it doesn't break the tests – it is an unrelated dependency issue as far as I can see.

**Comment by sebastien-fauvel** [comment]
Still the very principle of `strToChrArr` will lead to errors – you ought not to split up [Unicode extended grapheme clusters](http://unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries), consisting typically in one letter and one or more combining characters like accents. Splitting them up on two lines, for instance, will definitely lead to rendering issues – with one letter at the end of a line, and the accent at the beginning of the following line. `preg_match_all('/\X/u', $str, $matches)` (see http://php.net/manual/en/regexp.reference.unicode.php) would give you a list of grapheme clusters, that's how a Unicode string is supposed to be split up into "smallest parts".

But it looks like you have PDF rendering issues anyway, at least on my system, with both characters in a cluster (letter and accent) not being combined properly. `normalizer_normalize` is actually a workaround for this issue, as it will combine grapheme clusters into single characters, whenever possible. Could you please try to reproduce the issue, e.g. by creating a PDF with the text `"\xC3\x85"` (Å)?

**Pull request closed without merging**
